app/package-lock.json
app/package.json
app/src/handlers/census/CensusProxy.ts
app/src/services/census/CensusStreamService.ts
app/src/services/census/index.ts

Update ps2census to version 0.2.6

---

app/src/services/mongo/MongoDBConnection.ts
app/src/services/mongo/index.ts

Made it so it is inline with the IoC principle.
Also just to give an example for a model(note: mongoose use the active record implementation):
```js
const schema = new Schema {
name: String
};
@injectable()
class Kitten {
private readonly schema = schema;
private readonly model: Model;
public constructor(
private readonly mongoose: Mongoose,
) {
this.model = this.mongoose.mode(this.schema);
}
...
}
```

Fix statics within MongoDBConnection

---

app/src/services/mongo/MongoDBConnection.ts

While refactoring `MongoDBConnection` I forgot to remove the base `mongoose` instance.

Fix MongoDBConnection

---

app/src/services/census/CensusStreamService.ts

Moved the event listener subscribers.

Potential fix issue #52

---

app/src/constants/types.ts
app/src/handlers/aggregate/alert/AlertFacilityControlAggregate.ts
app/src/handlers/aggregate/index.ts
app/src/handlers/census/FacilityControlEventHandler.ts
app/src/models/aggregate/AlertFacilityControlAggregateModel.ts
app/src/services/census/CensusStreamService.ts
app/src/services/mongo/index.ts

#26 - AlertFacilityControlAggregate summing up each facility capture / defence event, additionally split out by Faction.

#26 - AlertFacilityControlAggregate

---

app/src/constants/types.ts
app/src/constants/world.ts
app/src/handlers/aggregate/alert/AlertFacilityControlAggregate.ts
app/src/handlers/aggregate/index.ts
app/src/handlers/aggregate/world/WorldFacilityControlAggregate.ts
app/src/models/aggregate/AlertFacilityControlAggregateModel.ts
app/src/models/aggregate/WorldFacilityControlAggregateModel.ts
app/src/services/mongo/index.ts

#26 - WorldFacilityControlAggregate

---

app/src/constants/types.ts
app/src/constants/world.ts
app/src/handlers/aggregate/alert/AlertPlayerAggregate.ts
app/src/handlers/aggregate/global/GlobalPlayerAggregate.ts
app/src/handlers/aggregate/index.ts
app/src/interfaces/AggregateHandlerInterface.ts
app/src/models/aggregate/AlertPlayerAggregateModel.ts
app/src/models/aggregate/GlobalPlayerAggregateModel.ts
app/src/services/census/CensusStreamService.ts
app/src/services/mongo/index.ts

Implementation of player combat indecies on an alert and global level. Global has a "world" property so we can get the top killers on a per-world basis if we so choose.

#26 - AlertPlayerAggregate & GlobalPlayerAggregate

---

app/src/constants/types.ts
app/src/handlers/aggregate/global/GlobalFactionCombatAggregate.ts
app/src/handlers/aggregate/index.ts
app/src/models/aggregate/alert/AlertFactionCombatAggregateModel.ts
app/src/models/aggregate/global/GlobalFactionCombatAggregateModel.ts
app/src/services/mongo/index.ts

#26 - Implemented GlobalFactionCombatAggregate and fixed issues with AlertFactionCombatAggregate

---

app/src/logger/DiscordTransport.ts

Implemented a queue for the DiscordTransport

---

src/bootstrap/Kernel.ts
src/index.ts
src/interfaces/ServiceInterface.ts
src/logger/DiscordTransport.ts
src/services/census/CensusStreamService.ts
src/services/subscribers/CensusEventSubscriberService.ts

Implemented Kernel termination code for services

---

src/data/AdminWebsocket/AdminWebsocketInstanceStartMessage.ts
src/handlers/messages/AdminWebsocketMessageHandler.ts
src/instances/PS2AlertsMetagameInstance.ts

#144 - Now supplying duration when manually starting instance

---

src/handlers/CharacterPresenceHandler.ts
src/handlers/census/PlayerLoginEventHandler.ts

Fixed logging, removed character presence event handler on player login so we no longer get issues with players not having any zones
Closes #140

#140 - Population metrics logging fix

---

package-lock.json
package.json
src/actions/PS2AlertsMetagameInstanceStartAction.ts
src/config/census.ts
src/data/Character.ts
src/data/Outfit.ts
src/handlers/aggregate/global/GlobalCharacterAggregate.ts
src/handlers/aggregate/global/GlobalClassAggregate.ts
src/handlers/aggregate/global/GlobalFactionCombatAggregate.ts
src/handlers/aggregate/global/GlobalOutfitAggregate.ts
src/handlers/aggregate/global/GlobalWeaponAggregate.ts
src/handlers/aggregate/instance/InstanceCharacterAggregate.ts
src/handlers/aggregate/instance/InstanceClassAggregate.ts
src/handlers/aggregate/instance/InstanceFactionCombatAggregate.ts
src/handlers/aggregate/instance/InstanceOutfitAggregate.ts
src/handlers/aggregate/instance/InstanceWeaponAggregate.ts
src/handlers/census/events/DeathEvent.ts
src/models/instance/InstanceDeathModel.ts
src/services/census/index.ts
src/types/CharacterWorldOutfitLeader.ts
src/victories/TerritoryVictoryCondition.ts

Bump ps2census to v0.5.6

---

src/authorities/CensusStaleConnectionWatcherAuthority.ts
src/authorities/index.ts
src/constants/types.ts
src/services/census/CensusStreamService.ts

Closes #155 
Also reduced Death timeout to 60 seconds.

#155 - Implement CensusStaleWatcherAuthority to handle different message types and customise times

---

src/handlers/aggregate/global/GlobalCharacterAggregate.ts
src/handlers/aggregate/global/GlobalClassAggregate.ts
src/handlers/aggregate/global/GlobalOutfitAggregate.ts
src/handlers/aggregate/global/GlobalWeaponAggregate.ts
src/handlers/aggregate/instance/InstanceCharacterAggregate.ts
src/handlers/aggregate/instance/InstanceClassAggregate.ts
src/handlers/aggregate/instance/InstanceOutfitAggregate.ts
src/handlers/aggregate/instance/InstanceWeaponAggregate.ts

This may explain why we occasionally miss a death!
Closes #176

#176 - Handle undetermined kill types

---

src/services/subscribers/CensusEventSubscriberService.ts

#174 - Implemented retry mechanism (not my best work) for Death and GainExperience events.

---

package-lock.json
package.json
src/actions/MetagameInstanceTerritoryStartAction.ts
src/calculators/BracketCalculator.ts
src/calculators/CalculatorInterface.ts
src/calculators/TerritoryCalculator.ts
src/constants/bracket.ts
src/constants/types.ts
src/factories/BracketCalculatorFactory.ts
src/factories/InstanceActionFactory.ts
src/factories/index.ts
src/handlers/InstanceHandler.ts
src/models/instance/InstanceMetagameTerritory.ts

#192 - Fuck timezones in the arse / Completed implementation of server brackets

---

src/config/census.ts
src/data/Character.ts
src/handlers/aggregate/VehicleAggregateHandler.ts
src/handlers/aggregate/VehicleDeathEventHandler.ts
src/handlers/aggregate/global/GlobalCharacterAggregate.ts
src/handlers/aggregate/global/GlobalOutfitAggregate.ts
src/handlers/aggregate/instance/InstanceCharacterAggregate.ts
src/handlers/aggregate/instance/InstanceOutfitAggregate.ts
src/handlers/census/DeathEventHandler.ts

#186 / #134 - Changes required to store character and outfit as objects & BR

---

src/config/census.ts
src/constants/fakeItem.ts
src/constants/types.ts
src/data/Item.ts
src/handlers/ItemBroker.ts
src/handlers/aggregate/global/GlobalCharacterAggregate.ts
src/handlers/aggregate/global/GlobalWeaponAggregate.ts
src/handlers/aggregate/instance/InstanceCharacterAggregate.ts
src/handlers/aggregate/instance/InstanceWeaponAggregate.ts
src/handlers/census/DeathEventHandler.ts
src/handlers/census/events/DeathEvent.ts
src/handlers/index.ts
src/interfaces/ItemBrokerInterface.ts
src/interfaces/ItemInterface.ts
src/services/subscribers/CensusEventSubscriberService.ts
src/types/CensusItem.ts

Closes #200 
Added item broker which collects any items we want, and caches the Census response for 24h.

#200 - Item Broker

---

src/authorities/InstanceAuthority.ts
src/authorities/PopulationAuthority.ts
src/handlers/CharacterPresenceHandler.ts
src/interfaces/CharacterPresenceHandlerInterface.ts

…with data surrounding that player, rather than entries per world and zone. This then collates the data and generates the stats based off data within keys, not by keys themselves.

Change the way population data is collected, creating keys by player 
